# NetSecureX Scan Configuration Example
# ====================================

# Target configuration
targets:
  - "192.168.1.0/24"
  - "10.0.0.1"
  - "example.com"

# Port scanning configuration
port_scan:
  enabled: true
  ports: "1-1000"
  timeout: 3.0
  max_concurrent: 100
  scan_type: "tcp"  # tcp, udp, syn

# SSL/TLS certificate analysis
ssl_analysis:
  enabled: true
  ports: [443, 8443, 993, 995]
  verify_hostname: true
  check_expiry: true
  min_key_size: 2048

# Banner grabbing
banner_grabbing:
  enabled: true
  timeout: 5.0
  common_ports: [21, 22, 23, 25, 53, 80, 110, 143, 443, 993, 995]
  custom_banners:
    - port: 80
      request: "GET / HTTP/1.1\r\nHost: {target}\r\n\r\n"
    - port: 443
      request: "GET / HTTP/1.1\r\nHost: {target}\r\n\r\n"

# CVE lookup configuration
cve_lookup:
  enabled: true
  max_results: 10
  min_score: 7.0
  sources: ["vulners", "nvd"]

# IP reputation checking
ip_reputation:
  enabled: true
  providers: ["abuseipdb", "virustotal", "ipqualityscore"]
  min_threat_score: 50

# Output configuration
output:
  format: "json"  # json, csv, table, markdown
  file: "scan_results_{timestamp}.json"
  include_raw_data: false
  compress: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "netsecurex_{timestamp}.log"
  max_size: "10MB"
  backup_count: 5

# Rate limiting
rate_limiting:
  requests_per_second: 10
  burst_size: 50
  respect_robots_txt: true

# Advanced options
advanced:
  user_agent: "NetSecureX/1.0.0"
  follow_redirects: true
  verify_ssl: true
  timeout_multiplier: 1.0
